# Default values for ej-fuse.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# BuildConfig git source
git:
  uri: https://github.com/garethahealy/fuse-helm-example.git
  ref: master

# BuildConfig mvn repo
maven:
  mirror_url: easyjet.com/artifactory

# Deployment image
image_repository: image-registry.openshift-image-registry.svc:5000
image_namespace: gahealy-testing
image_name: v1-ej-fuse-source
image_version: latest

# Deployment/HPA replica
replicas:
  min: 1
  max: 3

# Route
route: false

# PDB
pdb: false

# HPA
hpa:
  enabled: false
  cpuTarget: 200m
  memTarget: 300Mi

# ServiceMonitor
servicemonitor: false