---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: "{{ include "ej-fuse.fullname" . }}-source"
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ include "ej-fuse.fullname" . }}
  labels:
    {{- include "ej-fuse.labels" . | nindent 4 }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: {{ include "ej-fuse.fullname" . }}-source:latest
  runPolicy: Serial
  source:
    git:
      uri: {{ .Values.git.uri }}
      ref: {{ .Values.git.ref }}
    type: Git
  strategy:
    sourceStrategy:
      env:
        - name: BUILD_LOGLEVEL
          value: '5'
        - name: MAVEN_ARGS_APPEND
          value: "-pl ."
        - name: ARTIFACT_DIR
          value: "./target"
# https://access.redhat.com/documentation/en-us/red_hat_fuse/7.9/html/fuse_on_openshift_guide/installing-fuse-on-openshift-in-restricted-environment#deploy-and-run-quickstart-with-maven-mirror-url
#        - name: MAVEN_MIRROR_URL
#          value: {{ .Values.maven.mirror_url }}
        - name: ARTIFACT_COPY_ARGS
          value: "*.jar"
      from:
        kind: ImageStreamTag
        name: fuse-java-openshift-jdk11-rhel8:1.9
    type: Source
