---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ej-fuse.fullname" . }}
  labels:
    {{- include "ej-fuse.labels" . | nindent 4 }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicas.min }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- include "ej-fuse.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9779'
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "ej-fuse.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: {{ .Values.image_repository }}/{{ .Values.image_namespace }}/{{ .Values.image_name }}:{{ .Values.image_version }}
          imagePullPolicy: IfNotPresent
          name: {{ include "ej-fuse.name" . }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 5
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: prom
              containerPort: 9779
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 5
          resources:
            limits:
              cpu: '600m'
              memory: 1000Mi
            requests:
              cpu: '100m'
              memory: 100Mi