{{- if .Values.route }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "ej-fuse.fullname" . }}
  labels:
    {{- include "ej-fuse.labels" . | nindent 4 }}
spec:
  port:
    targetPort: tcp-8080
  to:
    kind: Service
    name: {{ include "ej-fuse.fullname" . }}
    weight: 100
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  wildcardPolicy: None
{{ end }}
