---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ej-fuse.fullname" . }}
  labels:
    {{- include "ej-fuse.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: tcp
    - name: prometheus
      port: 9779
      protocol: TCP
      targetPort: 9779
    - name: jolokia
      port: 8778
      protocol: TCP
      targetPort: 8778
  selector:
    {{- include "ej-fuse.selectorLabels" . | nindent 4 }}