apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: build
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ${APP_NAME}
    labels:
      app.kubernetes.io/name: ${APP_NAME}
  spec: { }
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app.kubernetes.io/name: ${APP_NAME}
    name: ${APP_NAME}-binary-build
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: fuse-java-openshift-jdk11-rhel8:1.9
      type: Source
parameters:
- name: APP_NAME
  required: true